version: '3.6'

networks:
    mytest:

services:
  postgres:
    image: postgres:$PG_IMAGE_TAG
    container_name: $PG_CONTAINER_NAME
    environment:
      - POSTGRES_DB=$PG_DB
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASSWD
    volumes:
      - $PG_HOST_VOLUME:/var/lib/postgresql/data
    networks:
      - mytest
    ports:
      - $PG_PORT:$PG_PORT
